#!/bin/bash
if [ -d "db/migrations" ]; then
    dir="migrations"
else
    dir="migrate"
fi

if [[ $# -lt 1 ]]; then
    vim $(ls -t db/$dir/* | head -1)
    exit
fi

files=$(find db/$dir -name "*$1*")
if [[ $(echo "$files" | wc -w) == 1 ]]; then
    vim $files
    exit
else
    select file in $files; do
        vim $file
        exit
    done
fi
