#!/bin/bash
if [ -d "db/migrations" ]; then
    dir="db/migrations"
elif [ -d "priv/repo/migrations" ]; then
    dir="priv/repo/migrations"
else
    dir="db/migrate"
fi

if [[ $# -lt 1 ]]; then
    vim $(ls -t $dir/* | head -1)
    exit
fi

files=$(find $dir -name "*$1*")
if [[ $(echo "$files" | wc -w) == 1 ]]; then
    vim $files
    exit
else
    select file in $files; do
        vim $file
        exit
    done
fi
